### PR TITLE
#165020077 Configure CircleCI with Codeclimate

### PR DESCRIPTION
**Pull request by coolbeatz71**
#### What does this PR do?
Configure CircleCI with Codeclimate
#### Description of Task to be completed?
- create circleCI config file
- send Codeclimate test report from circleCI
- create the Pull Request template
#### How should this be manually tested?

N/A

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?
[#165020077
](https://www.pivotaltracker.com/story/show/165020077)
#### Screenshots (if appropriate)

N/A

#### Questions:

N/A

### CODE REVIEW

**Comment by dkam26** [comment]
Why is circleCI failing? Do you mind fixing it?

**Comment by kipropbrian** [comment]
- Make sure the PT story ID is actually linking to the PT story.
- You also have the Github pull request template that you have not mentioned in your PR description.

**Review by gracelungu — APPROVED** [review]

**Comment by coolbeatz71** [comment]
> Why is circleCI failing? Do you mind fixing it?

Yes. @dkam26, it is because I don't have any test yet. I was just configuring it. I think I should put some dummy test to make it work

**Comment by coolbeatz71** [comment]
> * Make sure the PT story ID is actually linking to the PT story.
> * You also have the Github pull request template that you have not mentioned in your PR description.

Ohh yes, @kipropbrian I forgot to mention the template. I am fixing it ASAP.

**Comment by coolbeatz71** [comment]
> Why is circleCI failing? Do you mind fixing it?

Hey @dkam26, https://github.com/andela/ah-kgl-wakanda-frontend/pull/3/commits/8f256637f9fcbb24ef163aef87b455c95aca3be9 fixes circleci failure

**Comment by coolbeatz71** [comment]
> * Make sure the PT story ID is actually linking to the PT story.
> * You also have the Github pull request template that you have not mentioned in your PR description.

The pull request template was added to the PR https://github.com/andela/ah-kgl-wakanda-frontend/pull/3#issue-285320203

**Comment by dkam26** [comment]
https://github.com/andela/ah-kgl-wakanda-frontend/pull/3#issuecomment-499090814 .The story id isnt linkable to the pivot tracker story.FIx this!

**Comment by coolbeatz71** [comment]
> [#3 (comment)](https://github.com/andela/ah-kgl-wakanda-frontend/pull/3#issuecomment-499090814) .The story id isnt linkable to the pivot tracker story.FIx this!

It is now solved https://github.com/andela/ah-kgl-wakanda-frontend/pull/3#issue-285320203

**Pull request merged**
